### A Empy network
Making prediction with only one input

In [ ]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [ ]:
number_of_toes = [8.5, 9.5, 10, 9]

input = number_of_toes[0]

pred = neural_network(input, weight)
pred



0.8500000000000001

### Making a prediction with multiple inputs

In [ ]:
def w_sum(a, b):

    assert(len(a) == len(b))
    output = 0

    for i in range(len(a)):
        output += a[i] * b[i]

    return output

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
pred

0.9800000000000001

*Numpy* version

In [ ]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)

print(pred)


0.9800000000000001


### Making multiple output prediction using single input

In [ ]:
weights = [0.3, 0.2, 0.9] 

wlrec = [0.65, 0.8, 0.8, 0.9]

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert (len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    
    return output


def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

input = wlrec[0]

pred = neural_network(input, weights)
pred


[0.195, 0.13, 0.5850000000000001]

### Predicting with multiple inputs and outputs

In [ ]:
weight = [    [0.1, 0.1, -0.3],
                [0.1, 0.2, 0.0],
                [0.0, 1.3, 0.1] ]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0

    for i in range(len(a)):
        output += a[i] * b[i]

    return output 

def vect_mat_mul(vect, matrix):

    assert(len(vect) == len(matrix))
    output = [0, 0, 0]

    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])

    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred


input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input, weight)

print(pred)
        



[0.555, 0.9800000000000001, 0.9650000000000001]


### Predicting on Predictions

In [ ]:
# toes % win # fans
ih_wgt = [ [0.1, 0.2, -0.1], # hid[0]
[-0.1,0.1, 0.9], # hid[1]
[0.1, 0.4, 0.1] ] # hid[2]
#hid[0] hid[1] hid[2]

hp_wgt = [ [0.3, 1.1, -0.3], # hurt?
[0.1, 0.2, 0.0], # win?
[0.0, 1.3, 0.1] ] # sad?


weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input, weights)
print(pred)


[0.21350000000000002, 0.14500000000000002, 0.5065]


### NumPy Version

In [ ]:
import numpy as np


ih_wgt = np.array(
    [ [0.1, 0.2, -0.1], # hid[0]
    [-0.1,0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1] ] # hid[2]
) 

hp_wgt = np.array(
    [ [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] ] # sad?
)

weight = [ih_wgt, hp_wgt]

def neural_network(input, weight):

    hid = input.dot(weight[0])
    pred = hid.dot(weight[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input, weight)
print(pred)


[ 0.496  1.256 -0.286]


### NumPy Version

In [ ]:
import numpy as np
import random 

random.seed(42)

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])

c = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

d = np.zeros((2, 4))
e = np.random.rand(2, 5)


print(a)
print(b)
print(c)
print(d)
print(e)


[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.65067868 0.87809346 0.38680217 0.25386872 0.15169755]
 [0.65387519 0.8951537  0.44447276 0.89987928 0.72125181]]


In [ ]:
a = np.zeros((2, 4))
b = np.zeros((4, 3))

c = a.dot(b)

print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [ ]:
e = np.zeros((2, 1))
f = np.zeros((1, 3))

g = e.dot(f)
g.shape

(2, 3)

In [ ]:
h = np.zeros((5,4)).T
i = np.zeros((5, 6))

j = h.dot(i)
print(j.shape)

(4, 6)


In [ ]:
h = np.zeros((5,4))
i = np.zeros((5,6))

j = h.dot(i) # Throws error due to shape mismatch for multiplication
print(j.shape)

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)